name: CI Client

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/client/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        run: |
          cd packages/client
          yarn
          yarn build
          npx netlify-cli deploy --dir=packages/client/build --prod